server:
  port: 8080
  servlet:
    context-path: /ih
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/interface_helper?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    username: test
#    password: 111111
    url: jdbc:mysql://47.99.122.183:8011/egg_ih?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: asdf123456#
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.egg.ih.db.model
  configuration:
    map-underscore-to-camel-case: true

# 当前路径
current:
  path: D:\\code\\github\\egg-interface-helper